name: Docker Build

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t github-actions-attestation .

      - name: Run Docker container
        run: docker run github-actions-attestation
